#!/usr/bin/env python
"""Fetch the OFFICIAL UNQOVER data (Li et al. 2020, Findings of EMNLP).

Official repo : https://github.com/allenai/unqover
Pinned commit : 3e47969b78acc0de436f9d17c9ab1b2f6a108ff0  (2021-07-06)
Bulk data.zip : https://ai2-public-datasets.s3.amazonaws.com/unqover/data.zip
                (~5.9 GB; pre-generated QA/LM *predictions*, which we do NOT need
                 because we run OUR model -- LLaDA -- via unqover_eval.py)

We only need the underspecified *questions* (the `*.source.json` templates), so
this downloader CLONES the (small) official repo at the pinned commit and runs
its own generator `templates.generate_underspecified_templates` to produce the
`*.source.json` files -- i.e. the exact official data, generated by the official
code, not fabricated here.

Squad-style slots are used (full group names as answer choices, e.g. "African",
"Jewish") because our harness generates free text and parses the chosen SUBJECT;
the `*_lm` slots (single masked token) are only for masked-LM scoring.

If git / network / generation is unavailable, we print the exact manual steps
and the official URLs and exit non-zero WITHOUT writing any placeholder data.

Cache layout (all under data/unqover/, gitignored):
    data/unqover/unqover_repo/                 # cloned official repo (@ pinned commit)
    data/unqover/generated/<class>.source.json # generated official questions

CPU only, no model.  Example:
    python unqover/download_unqover.py --classes ethnicity religion
    python unqover/download_unqover.py --classes all
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(HERE), "data", "unqover")
REPO_DIR = os.path.join(DATA, "unqover_repo")
GEN_DIR = os.path.join(DATA, "generated")

REPO_URL = "https://github.com/allenai/unqover.git"
COMMIT = "3e47969b78acc0de436f9d17c9ab1b2f6a108ff0"
DATA_ZIP = "https://ai2-public-datasets.s3.amazonaws.com/unqover/data.zip"

# class -> (subj list, activity/attribute list, slot template).  Squad-style
# (full-name answer choices) taken verbatim from scripts/generate_questions.sh.
CLASS_SPEC = {
    "ethnicity": ("ethnicity", "biased_ethnicity", "ethnicity_noact"),
    "religion":  ("religion",  "biased_religion",  "religion_noact"),
    "country":   ("country",   "biased_country",   "country_noact"),
    "gender":    ("mixed_gender", "occupation_rev1", "gender_noact"),
}


def _run(cmd, cwd=None):
    print("+ " + " ".join(cmd))
    return subprocess.run(cmd, cwd=cwd, check=True)


def manual_instructions(reason):
    print("\n" + "!" * 72)
    print(f"AUTOMATIC FETCH FAILED: {reason}")
    print("!" * 72)
    print("Do this manually (official sources):")
    print(f"  1) git clone {REPO_URL} {REPO_DIR}")
    print(f"  2) cd {REPO_DIR} && git checkout {COMMIT}")
    print("  3) For each class run the official generator, e.g. ethnicity:")
    print(f"     python -m templates.generate_underspecified_templates \\")
    print(f"       --template_type slot_act_map --subj ethnicity \\")
    print(f"       --act biased_ethnicity --slot ethnicity_noact \\")
    print(f"       --output {GEN_DIR}/ethnicity.source.json")
    print("     (subj/act/slot per class: see CLASS_SPEC in this file)")
    print(f"  Alternatively the full pre-generated bundle (~5.9 GB, includes QA/LM")
    print(f"  predictions we DON'T need) is at:\n     {DATA_ZIP}")
    print("Expected output path this repo consumes:")
    print(f"     {GEN_DIR}/<class>.source.json")
    print("!" * 72)


def ensure_repo():
    if os.path.isdir(os.path.join(REPO_DIR, "templates")):
        print(f"repo present: {REPO_DIR}")
        return
    os.makedirs(DATA, exist_ok=True)
    _run(["git", "clone", REPO_URL, REPO_DIR])
    # Pin the commit (best-effort; a fresh full clone contains it).
    try:
        _run(["git", "checkout", COMMIT], cwd=REPO_DIR)
    except subprocess.CalledProcessError:
        _run(["git", "fetch", "--depth", "1", "origin", COMMIT], cwd=REPO_DIR)
        _run(["git", "checkout", COMMIT], cwd=REPO_DIR)


def generate(cls):
    subj, act, slot = CLASS_SPEC[cls]
    os.makedirs(GEN_DIR, exist_ok=True)
    out = os.path.join(GEN_DIR, f"{cls}.source.json")
    if os.path.exists(out) and os.path.getsize(out) > 0:
        print(f"[{cls}] already generated -> {out}")
        return out
    cmd = [sys.executable, "-m", "templates.generate_underspecified_templates",
           "--template_type", "slot_act_map", "--subj", subj,
           "--act", act, "--slot", slot, "--output", out]
    _run(cmd, cwd=REPO_DIR)
    return out


def main():
    ap = argparse.ArgumentParser(description="Fetch official UNQOVER source questions.")
    ap.add_argument("--classes", nargs="+", default=["ethnicity", "religion"],
                    help="subset of %s, or 'all'" % list(CLASS_SPEC))
    args = ap.parse_args()
    classes = list(CLASS_SPEC) if args.classes == ["all"] else args.classes
    bad = [c for c in classes if c not in CLASS_SPEC]
    if bad:
        sys.exit(f"unknown class(es) {bad}; choose from {list(CLASS_SPEC)} or 'all'")

    try:
        ensure_repo()
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        manual_instructions(f"clone failed ({e})")
        sys.exit(1)

    outs = []
    for c in classes:
        try:
            outs.append(generate(c))
        except subprocess.CalledProcessError as e:
            manual_instructions(f"generation of '{c}' failed ({e})")
            sys.exit(1)

    print("\nGenerated official UNQOVER source files:")
    for o in outs:
        print(f"  {o}  ({os.path.getsize(o) // 1024} KB)")
    print("\nNext: convert to our --items format, e.g.")
    print(f"  python {os.path.join(HERE, 'unqover_loader.py')} \\")
    print(f"    --source {outs[0]} --out {os.path.join(DATA, os.path.basename(outs[0]).replace('.source.json', '.items.jsonl'))} --limit 2000")


if __name__ == "__main__":
    main()
